### ISSUE TITLE
OpenWeather UV Index API Call Deprecated

### ISSUE THREAD

**Issue by rjshiffer** [G6EJD/ESP32_Advanced_Weather_Server#3]
From information on the OpenWeather.org site:

 >The product will retire on 1st April 2021, please find UV data in One Call API.
 >One Call API includes current, hourly forecast for 7 days and 5 days historical UV data.
[]https://openweathermap.org/api/uvi

Here's the One Call API documentation:
[]https://openweathermap.org/api/one-call-api

Changes required (at a minimum):
1. setup():  Change call to obtain_wx_data to specify "onecall" api.
2. DecodeWeather(): Change Type == "uvi" to Type == "onecall" and get uvi from One Call JSON format.
3. (Optional) obtain_wx_data(): Add "&exclude=minutely,hourly,daily,alerts" to "onecall" URI request to minimize JSON response.

Sorry I'm not a  proficient git user and don't trust myself to directly submit the code changes.

**Comment by G6EJD** [comment]
Thank you for the advanced warning, I’ll look at this soon.

**Comment by G6EJD** [comment]
I've updated the version now, I'll look at the 'onecall' API to see if it could provide all the data in one access. Thank you.
