### ISSUE TITLE
[future request] ESP8266

### ISSUE THREAD

**Issue by SA7BNT** [G6EJD/ESP32_Advanced_Weather_Server#4]
Hey David,

is it possible that the "Advanced Weather Server" also can run on a ESP8266 ??
After i mod some include i still getting 

> compilation terminated.
exit status 1
Error compiling for board Generic ESP8266 Module.

Is there a chance to get it run on the ESP8266

Best from Sweden
SA7BNT de Tim
<img width="1440" alt="Bildschirmfoto 2022-02-01 um 22 11 17" src="https://user-images.githubusercontent.com/35367117/152052109-42b43e68-1082-46ea-b25b-06b21cafd096.png">

**Comment by G6EJD** [comment]
Hello Tim,

That sounds like an upload problem rather than compilation error, did you try a different board type. What board type do you have?

Regards

David

**Comment by SA7BNT** [comment]
> 

Hey David,

thanks for your replay.
I just running a Verify in the Arduino software not a upload. 
As board type im running Generic ESP8266 Module.
Same if im running 

> compilation terminated.
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).
![photo_2022-02-01 22 30 08](https://user-images.githubusercontent.com/35367117/152055505-2ab472f9-7862-4668-b2a6-9226c0855898.jpeg)

**Comment by SA7BNT** [comment]
Getting a bit longer.

[log_output.txt](https://github.com/G6EJD/ESP32_Advanced_Weather_Server/files/7982510/log_output.txt)

**Comment by G6EJD** [comment]
I’ll have a look at the code today there are some basic errors, SPIFFS is no longer compatible with the ESP8266 compiler, so use littleFS instead, some time functions are not supported by the 8266 compiler and in the WiFi startup section there are reconnect functions that are not supported on the 8266, it’s not as bad as it might look.

**Comment by SA7BNT** [comment]
> I’ll have a look at the code today there are some basic errors, SPIFFS is no longer compatible with the ESP8266 compiler, so use littleFS instead, some time functions are not supported by the 8266 compiler and in the WiFi startup section there are reconnect functions that are not supported on the 8266, it’s not as bad as it might look.

Awsome, looking forward to try. 

Best

**Comment by G6EJD** [comment]
I've upload an ESP8266 version, it has taken a lot of work. I've had to redo the time functions, and move a lot of text to the Flash memory using the F() macro, so Serial.println("hello"); becomes Serial.println(F("hello")); and saves 5-bytes of ram, I've saved 14K but all this is stretching the ESP8266 to it's limits, I have not texted the code, but it compiles and should work.

**Comment by SA7BNT** [comment]
> I've upload an ESP8266 version, it has taken a lot of work. I've had to redo the time functions, and move a lot of text to the Flash memory using the F() macro, so Serial.println("hello"); becomes Serial.println(F("hello")); and saves 5-bytes of ram, I've saved 14K but all this is stretching the ESP8266 to it's limits, I have not texted the code, but it compiles and should work.

Thanks David i will try it right now

Best and 73
SA7BNT de Tim

**Comment by SA7BNT** [comment]
Running out of memory. So it seems that it will not work on ESP8266

> WiFi connected at: 192.168.5.67
WiFi Started...
mDNS responder started
Device name: wxserver
Time started...
/data/2.5/weather?lat=57.6436&lon=15.2712&APPID=ad315f2ff1c8ee83e35227416fc3a467&mode=json&units=metric&lang=se

Creating object...and deserializeJson() failed: NoMemory
/data/2.5/forecast?lat=57.6436&lon=15.2712&APPID=ad315f2ff1c8ee83e35227416fc3a467&mode=json&units=metric&lang=se&cnt=40

Creating object...and deserializeJson() failed: NoMemory
/data/2.5/onecall?lat=57.6436&lon=15.2712&APPID=ad315f2ff1c8ee83e35227416fc3a467&mode=json&units=metric&lang=se&cnt=40

Creating object...and deserializeJson() failed: NoMemory
/data/2.5/weather?lat=57.6436&lon=15.2712&APPID=ad315f2ff1c8ee83e35227416fc3a467&mode=json&units=metric&lang=se

Creating object...and deserializeJson() failed: NoMemory
/data/2.5/forecast?lat=57.6436&lon=15.2712&APPID=ad315f2ff1c8ee83e35227416fc3a467&mode=json&units=metric&lang=se&cnt=40

Creating object...and deserializeJson() failed: NoMemory
/data/2.5/onecall?lat=57.6436&lon=15.2712&APPID=ad315f2ff1c8ee83e35227416fc3a467&mode=json&units=metric&lang=se&cnt=40

Creating object...and deserializeJson() failed: NoMemory

**Comment by G6EJD** [comment]
Not an unexpected result, the json decoded has run out of RAM to deserialise the quite large OWN json data, that’s as far as it can go, the only solution is a $3 ESP32 that has huge amounts of RAM by comparison.

**Comment by SA7BNT** [comment]
> Not an unexpected result, the json decoder has run out of RAM to deserialise the quite large OWM json data, that’s as far as it can go, the only solution is a $3 ESP32 that has huge amounts of RAM by comparison.

And that is the way i think i will go. 
Thanks for trying.

Best

**Comment by G6EJD** [comment]
There’s nothing more I can do, 73
